const data = [
  {
    id: 1,
    fullName: 'Callean Raylton',
    avatar:
      'https://robohash.org/voluptasdoloremcorporis.png?size=50x50&set=set1',
    university: 'European Carolus Magnus University',
    department: 'Human Resources',
  },
  {
    id: 2,
    fullName: "Claretta D'Errico",
    avatar: 'https://robohash.org/sitnostrumnemo.png?size=50x50&set=set1',
    university: 'Atomi College',
    department: 'Research and Development',
  },
  {
    id: 3,
    fullName: 'Warren Senton',
    avatar:
      'https://robohash.org/aspernaturcommodiipsum.png?size=50x50&set=set1',
    university: 'Universidad Valle del Momboy',
    department: 'Product Management',
  },
  {
    id: 4,
    fullName: 'Eldredge Bennallck',
    avatar: 'https://robohash.org/quaeratearumamet.png?size=50x50&set=set1',
    university: 'University of Tartu',
    department: 'Research and Development',
  },
  {
    id: 5,
    fullName: 'Devy Cleugher',
    avatar: 'https://robohash.org/temporamolestiaeet.png?size=50x50&set=set1',
    university: 'Constantin Brancoveanu University Pitesti',
    department: 'Legal',
  },
  {
    id: 6,
    fullName: 'Ninnette Uttley',
    avatar: 'https://robohash.org/ducimusutsuscipit.png?size=50x50&set=set1',
    university: 'Osaka City University',
    department: 'Training',
  },
  {
    id: 7,
    fullName: 'Leoline Beardsdale',
    avatar:
      'https://robohash.org/excepturisuntexercitationem.png?size=50x50&set=set1',
    university: 'Gift University',
    department: 'Marketing',
  },
  {
    id: 8,
    fullName: 'Zulema Tipens',
    avatar: 'https://robohash.org/eumquiscorporis.png?size=50x50&set=set1',
    university: 'International Academy of  Merchandising and Design Tampa',
    department: 'Legal',
  },
  {
    id: 9,
    fullName: 'Emery Noke',
    avatar: 'https://robohash.org/quivoluptatesit.png?size=50x50&set=set1',
    university: 'Universidad del Pacífico',
    department: 'Sales',
  },
  {
    id: 10,
    fullName: 'Tami Lamers',
    avatar: 'https://robohash.org/inmagniquam.png?size=50x50&set=set1',
    university: 'Stetson University',
    department: 'Business Development',
  },
  {
    id: 11,
    fullName: 'Brocky Daventry',
    avatar: 'https://robohash.org/eiusaliquidnam.png?size=50x50&set=set1',
    university: 'Yazd Medical University',
    department: 'Marketing',
  },
  {
    id: 12,
    fullName: 'Lorilee Baalham',
    avatar: 'https://robohash.org/quisitsimilique.png?size=50x50&set=set1',
    university: 'Juniata College',
    department: 'Human Resources',
  },
  {
    id: 13,
    fullName: 'Mab Breacher',
    avatar: 'https://robohash.org/hicexcepturiminus.png?size=50x50&set=set1',
    university: 'University of Brighton',
    department: 'Sales',
  },
  {
    id: 14,
    fullName: 'Ramonda Copper',
    avatar: 'https://robohash.org/quiipsasunt.png?size=50x50&set=set1',
    university: 'University of Texas Medical Branch Galveston',
    department: 'Support',
  },
  {
    id: 15,
    fullName: 'Kathryne McRill',
    avatar: 'https://robohash.org/suntmolestiaenihil.png?size=50x50&set=set1',
    university: 'Texas A&M University - Commerce',
    department: 'Services',
  },
  {
    id: 16,
    fullName: 'Reinald Odby',
    avatar: 'https://robohash.org/quisvelut.png?size=50x50&set=set1',
    university: 'Zawiya Academy',
    department: 'Training',
  },
  {
    id: 17,
    fullName: 'Courtnay Hurle',
    avatar:
      'https://robohash.org/distinctiorepudiandaedolorem.png?size=50x50&set=set1',
    university: 'Moscow State University M.V. Lomonosov',
    department: 'Engineering',
  },
  {
    id: 18,
    fullName: 'Keeley McNeil',
    avatar: 'https://robohash.org/necessitatibuseumnon.png?size=50x50&set=set1',
    university: 'Brno University of Technology',
    department: 'Sales',
  },
  {
    id: 19,
    fullName: 'Selma Nawton',
    avatar: 'https://robohash.org/voluptatematqueenim.png?size=50x50&set=set1',
    university: "Chukyo Women's University",
    department: 'Accounting',
  },
  {
    id: 20,
    fullName: 'Jacquenetta Lavallin',
    avatar: 'https://robohash.org/placeatquiaut.png?size=50x50&set=set1',
    university: 'IBAIS University',
    department: 'Sales',
  },
  {
    id: 21,
    fullName: 'Malachi Grocock',
    avatar: 'https://robohash.org/beataeadipiscirerum.png?size=50x50&set=set1',
    university: 'Central University of Finance and Economics',
    department: 'Human Resources',
  },
  {
    id: 22,
    fullName: 'Aryn Shotboult',
    avatar: 'https://robohash.org/itaqueetenim.png?size=50x50&set=set1',
    university: 'Trinity College of Florida',
    department: 'Product Management',
  },
  {
    id: 23,
    fullName: 'Cassey Hunn',
    avatar: 'https://robohash.org/doloresautet.png?size=50x50&set=set1',
    university: 'Webster University',
    department: 'Sales',
  },
  {
    id: 24,
    fullName: 'Redford Belleny',
    avatar: 'https://robohash.org/totamdeserunttenetur.png?size=50x50&set=set1',
    university: 'Catholic University of Pusan',
    department: 'Sales',
  },
  {
    id: 25,
    fullName: 'Noellyn Rosbottom',
    avatar: 'https://robohash.org/voluptatumnatushic.png?size=50x50&set=set1',
    university: 'Istanbul Bilgi University',
    department: 'Accounting',
  },
  {
    id: 26,
    fullName: 'Bennie Chitham',
    avatar: 'https://robohash.org/voluptateessebeatae.png?size=50x50&set=set1',
    university: 'University of Texas at Dallas',
    department: 'Research and Development',
  },
  {
    id: 27,
    fullName: 'Andros Wison',
    avatar: 'https://robohash.org/doloresautemminima.png?size=50x50&set=set1',
    university: 'Hazara University',
    department: 'Legal',
  },
  {
    id: 28,
    fullName: 'Morgen Wagen',
    avatar: 'https://robohash.org/animiquiamolestias.png?size=50x50&set=set1',
    university: 'Tanta University',
    department: 'Engineering',
  },
  {
    id: 29,
    fullName: 'Carroll Braunfeld',
    avatar: 'https://robohash.org/consequunturnequecum.png?size=50x50&set=set1',
    university: 'Universidad Nacional Experimental del Táchira',
    department: 'Product Management',
  },
  {
    id: 30,
    fullName: 'Jasmine Zukierman',
    avatar: 'https://robohash.org/nobisnihilex.png?size=50x50&set=set1',
    university: 'Christ University',
    department: 'Research and Development',
  },
  {
    id: 31,
    fullName: 'Stafani Pietrowski',
    avatar: 'https://robohash.org/adipisciquosearum.png?size=50x50&set=set1',
    university: 'Hamilton College',
    department: 'Business Development',
  },
  {
    id: 32,
    fullName: 'Anitra Jessard',
    avatar: 'https://robohash.org/blanditiisautratione.png?size=50x50&set=set1',
    university: 'University of Illinois at Chicago',
    department: 'Engineering',
  },
  {
    id: 33,
    fullName: 'Sibilla Syddon',
    avatar: 'https://robohash.org/autquodconsequatur.png?size=50x50&set=set1',
    university: 'Dnepropetrovsk National University of Railway Transport',
    department: 'Legal',
  },
  {
    id: 34,
    fullName: 'Ives Whyborn',
    avatar:
      'https://robohash.org/estaccusamustemporibus.png?size=50x50&set=set1',
    university: 'College of William and Mary',
    department: 'Research and Development',
  },
  {
    id: 35,
    fullName: 'George Petrulis',
    avatar: 'https://robohash.org/oditquaeratut.png?size=50x50&set=set1',
    university: 'Carleton College',
    department: 'Training',
  },
  {
    id: 36,
    fullName: 'Damiano Moine',
    avatar: 'https://robohash.org/nonvoluptatumeveniet.png?size=50x50&set=set1',
    university: 'North China Electric Power University',
    department: 'Training',
  },
  {
    id: 37,
    fullName: "Koral O' Mulderrig",
    avatar: 'https://robohash.org/ipsametet.png?size=50x50&set=set1',
    university: 'Fachhochschule Weihenstephan',
    department: 'Research and Development',
  },
  {
    id: 38,
    fullName: 'Helga Geerits',
    avatar: 'https://robohash.org/velcorporiscorrupti.png?size=50x50&set=set1',
    university: 'Macau Polytechnic Institute',
    department: 'Product Management',
  },
  {
    id: 39,
    fullName: 'Fancy Ottosen',
    avatar:
      'https://robohash.org/excepturiametconsequatur.png?size=50x50&set=set1',
    university: 'Marquette University',
    department: 'Engineering',
  },
  {
    id: 40,
    fullName: 'Margarette Riden',
    avatar: 'https://robohash.org/doloremetnon.png?size=50x50&set=set1',
    university: 'Universitat de Vic',
    department: 'Marketing',
  },
  {
    id: 41,
    fullName: 'Ag Yarwood',
    avatar: 'https://robohash.org/suntvoluptasquasi.png?size=50x50&set=set1',
    university: 'Kursk State University',
    department: 'Business Development',
  },
  {
    id: 42,
    fullName: 'Hephzibah Groves',
    avatar: 'https://robohash.org/quisintducimus.png?size=50x50&set=set1',
    university: 'Kotelawala Defence University',
    department: 'Services',
  },
  {
    id: 43,
    fullName: 'Beret Le Lievre',
    avatar: 'https://robohash.org/ipsafugiatsit.png?size=50x50&set=set1',
    university: 'Dakota Wesleyan University',
    department: 'Business Development',
  },
  {
    id: 44,
    fullName: 'Bunnie Bosson',
    avatar:
      'https://robohash.org/voluptatemasperioreset.png?size=50x50&set=set1',
    university: 'Lutherische Theologische Hochschule Oberursel',
    department: 'Sales',
  },
  {
    id: 45,
    fullName: 'Lalo Turbill',
    avatar: 'https://robohash.org/solutavoluptatesfuga.png?size=50x50&set=set1',
    university: 'Université Paris Nanterre (Paris X)',
    department: 'Human Resources',
  },
  {
    id: 46,
    fullName: 'Poppy Coverlyn',
    avatar: 'https://robohash.org/quiadoloremrem.png?size=50x50&set=set1',
    university: 'Technological Education Institute of Kozani',
    department: 'Research and Development',
  },
  {
    id: 47,
    fullName: 'Yorgos Ference',
    avatar:
      'https://robohash.org/quiaconsequaturquaerat.png?size=50x50&set=set1',
    university: 'Jimma University',
    department: 'Marketing',
  },
  {
    id: 48,
    fullName: 'Rolf Brumwell',
    avatar: 'https://robohash.org/quiasaepevoluptate.png?size=50x50&set=set1',
    university: 'University of Kashmir',
    department: 'Research and Development',
  },
  {
    id: 49,
    fullName: 'Harald Forsyth',
    avatar: 'https://robohash.org/quasindicta.png?size=50x50&set=set1',
    university: 'Open University of Tanzania',
    department: 'Accounting',
  },
  {
    id: 50,
    fullName: 'Karel Coopman',
    avatar: 'https://robohash.org/magnamoptioaut.png?size=50x50&set=set1',
    university: "King Mongkut's University of Technology North Bangkok",
    department: 'Legal',
  },
  {
    id: 51,
    fullName: 'Welsh Cleen',
    avatar: 'https://robohash.org/velitvoluptatesqui.png?size=50x50&set=set1',
    university: 'University of St. Thomas, Houston',
    department: 'Legal',
  },
  {
    id: 52,
    fullName: 'Carrissa Bernollet',
    avatar: 'https://robohash.org/maximevoluptatesest.png?size=50x50&set=set1',
    university: 'Tilak Maharashtra Vidyapeeth',
    department: 'Accounting',
  },
  {
    id: 53,
    fullName: 'Kynthia Gerring',
    avatar:
      'https://robohash.org/necessitatibusporroerror.png?size=50x50&set=set1',
    university: 'Universidade Católica de Salvador',
    department: 'Business Development',
  },
  {
    id: 54,
    fullName: 'Evan Lebrun',
    avatar: 'https://robohash.org/doloremitaqueaut.png?size=50x50&set=set1',
    university: 'Kwara State Polytecnic',
    department: 'Human Resources',
  },
  {
    id: 55,
    fullName: 'Dionis Jankowski',
    avatar:
      'https://robohash.org/aspernaturvoluptatemvelit.png?size=50x50&set=set1',
    university: 'Lock Haven University of Pennsylvania',
    department: 'Training',
  },
  {
    id: 56,
    fullName: 'Georges Woof',
    avatar: 'https://robohash.org/etetomnis.png?size=50x50&set=set1',
    university: 'Florida Metropolitan University, Tampa College Brandon',
    department: 'Support',
  },
  {
    id: 57,
    fullName: 'Aluino Enrico',
    avatar: 'https://robohash.org/eiusexet.png?size=50x50&set=set1',
    university: 'University of Anbar',
    department: 'Support',
  },
  {
    id: 58,
    fullName: 'Shari Darlow',
    avatar: 'https://robohash.org/utblanditiisquisquam.png?size=50x50&set=set1',
    university: 'Columbia International University',
    department: 'Business Development',
  },
  {
    id: 59,
    fullName: 'Lalo Sollowaye',
    avatar:
      'https://robohash.org/nesciuntdeseruntlabore.png?size=50x50&set=set1',
    university: 'Universität Osnabrück',
    department: 'Accounting',
  },
  {
    id: 60,
    fullName: 'Maudie Perott',
    avatar:
      'https://robohash.org/aspernaturconsecteturut.png?size=50x50&set=set1',
    university: 'Tokyo University of Pharmacy and Life Science',
    department: 'Support',
  },
  {
    id: 61,
    fullName: 'Georges Pagnin',
    avatar: 'https://robohash.org/magnamquoaut.png?size=50x50&set=set1',
    university: 'Tuva State University',
    department: 'Support',
  },
  {
    id: 62,
    fullName: 'Grayce Russi',
    avatar:
      'https://robohash.org/quiadoloresaspernatur.png?size=50x50&set=set1',
    university: 'Akaki Tsereteli State University',
    department: 'Support',
  },
  {
    id: 63,
    fullName: 'Albrecht Pendrid',
    avatar: 'https://robohash.org/aliberoblanditiis.png?size=50x50&set=set1',
    university: 'Rizal Technological University',
    department: 'Training',
  },
  {
    id: 64,
    fullName: 'Arnoldo Mowsdale',
    avatar:
      'https://robohash.org/exercitationemetdeleniti.png?size=50x50&set=set1',
    university: 'Universidade Federal de Lavras',
    department: 'Engineering',
  },
  {
    id: 65,
    fullName: 'Cris Huonic',
    avatar: 'https://robohash.org/natusnonsimilique.png?size=50x50&set=set1',
    university: 'Beijing Polytechnic University',
    department: 'Sales',
  },
  {
    id: 66,
    fullName: 'Trenton Tomadoni',
    avatar: 'https://robohash.org/sitenimest.png?size=50x50&set=set1',
    university: 'University of Texas Pan American',
    department: 'Support',
  },
  {
    id: 67,
    fullName: 'Mersey Allport',
    avatar: 'https://robohash.org/evenietsedrem.png?size=50x50&set=set1',
    university: 'Intercollege',
    department: 'Business Development',
  },
  {
    id: 68,
    fullName: 'Peyton Faulds',
    avatar: 'https://robohash.org/repellatnoneaque.png?size=50x50&set=set1',
    university: 'Andhra University',
    department: 'Business Development',
  },
  {
    id: 69,
    fullName: 'Bradford Cray',
    avatar: 'https://robohash.org/illoassumendaquia.png?size=50x50&set=set1',
    university: 'Sumgait State University',
    department: 'Engineering',
  },
  {
    id: 70,
    fullName: 'Dorisa Summerhayes',
    avatar: 'https://robohash.org/culpaetquod.png?size=50x50&set=set1',
    university: 'University of Akron',
    department: 'Legal',
  },
  {
    id: 71,
    fullName: 'Gregor Dziwisz',
    avatar: 'https://robohash.org/eiusmagnirem.png?size=50x50&set=set1',
    university: 'Zhejiang Forestry University',
    department: 'Human Resources',
  },
  {
    id: 72,
    fullName: 'Marchall Samart',
    avatar: 'https://robohash.org/etetpossimus.png?size=50x50&set=set1',
    university: 'Hubei University',
    department: 'Sales',
  },
  {
    id: 73,
    fullName: 'Minnnie Angric',
    avatar: 'https://robohash.org/officiamolestiaeut.png?size=50x50&set=set1',
    university: 'American InterContinental University Online',
    department: 'Training',
  },
  {
    id: 74,
    fullName: 'Langston Towner',
    avatar:
      'https://robohash.org/beataenatusreiciendis.png?size=50x50&set=set1',
    university: 'Cag University',
    department: 'Business Development',
  },
  {
    id: 75,
    fullName: 'Gustaf Sartin',
    avatar: 'https://robohash.org/culparepudiandaeat.png?size=50x50&set=set1',
    university: 'Saigon University',
    department: 'Accounting',
  },
  {
    id: 76,
    fullName: 'Marcel Anchor',
    avatar: 'https://robohash.org/blanditiisipsumearum.png?size=50x50&set=set1',
    university: 'Universidad de América Bogotá',
    department: 'Product Management',
  },
  {
    id: 77,
    fullName: 'Lauree Bohlens',
    avatar: 'https://robohash.org/quaenihilnumquam.png?size=50x50&set=set1',
    university: 'Courtauld Institute of Art, University of London',
    department: 'Human Resources',
  },
  {
    id: 78,
    fullName: 'Alyosha Jay',
    avatar:
      'https://robohash.org/consecteturreprehenderittempora.png?size=50x50&set=set1',
    university: 'Universidad San Juan de la Cruz',
    department: 'Legal',
  },
  {
    id: 79,
    fullName: 'Faith Daniau',
    avatar: 'https://robohash.org/velquiamolestias.png?size=50x50&set=set1',
    university: 'Brown University',
    department: 'Services',
  },
  {
    id: 80,
    fullName: 'Bradley Pallatina',
    avatar: 'https://robohash.org/autquiqui.png?size=50x50&set=set1',
    university: 'Rajshahi University of Engineering and Technology',
    department: 'Support',
  },
  {
    id: 81,
    fullName: 'Margi Haken',
    avatar: 'https://robohash.org/sednamtotam.png?size=50x50&set=set1',
    university: 'Southwest Missouri State University - West Plains',
    department: 'Product Management',
  },
  {
    id: 82,
    fullName: 'Katerine Tarborn',
    avatar: 'https://robohash.org/dignissimosiddolore.png?size=50x50&set=set1',
    university: 'Universitas Bunda Mulia Jakarta',
    department: 'Research and Development',
  },
  {
    id: 83,
    fullName: 'Phillipp Pendry',
    avatar:
      'https://robohash.org/nostrumpraesentiumiusto.png?size=50x50&set=set1',
    university: 'Universidade Estadual de Campinas',
    department: 'Legal',
  },
  {
    id: 84,
    fullName: 'Seana Scardafield',
    avatar: 'https://robohash.org/quisolutaut.png?size=50x50&set=set1',
    university: 'Universidad de Sonsonate',
    department: 'Product Management',
  },
  {
    id: 85,
    fullName: 'Hagan Swanger',
    avatar: 'https://robohash.org/ipsaipsamsit.png?size=50x50&set=set1',
    university: 'Palm Beach Atlantic University',
    department: 'Product Management',
  },
  {
    id: 86,
    fullName: 'Katy Bengtsson',
    avatar: 'https://robohash.org/molestiaeestporro.png?size=50x50&set=set1',
    university: 'Université de Provence (Aix-Marseille I)',
    department: 'Support',
  },
  {
    id: 87,
    fullName: 'Ree Flips',
    avatar: 'https://robohash.org/voluptatemquisid.png?size=50x50&set=set1',
    university: 'Universiteit Antwerpen Management School',
    department: 'Marketing',
  },
  {
    id: 88,
    fullName: 'Arlan Davidof',
    avatar: 'https://robohash.org/pariaturutaut.png?size=50x50&set=set1',
    university: 'Universitas Ibn Chaldun Jakarta',
    department: 'Business Development',
  },
  {
    id: 89,
    fullName: 'Fania Gammons',
    avatar: 'https://robohash.org/perspiciatisistefuga.png?size=50x50&set=set1',
    university: 'Central Police University',
    department: 'Research and Development',
  },
  {
    id: 90,
    fullName: 'Catie Cornuau',
    avatar: 'https://robohash.org/sitautemqui.png?size=50x50&set=set1',
    university: 'Tashkent State University of Economics',
    department: 'Accounting',
  },
  {
    id: 91,
    fullName: 'Kath Crosen',
    avatar: 'https://robohash.org/nonquialiquam.png?size=50x50&set=set1',
    university: 'Escuela Superior Politécnica del Litoral',
    department: 'Product Management',
  },
  {
    id: 92,
    fullName: 'Spense Deackes',
    avatar: 'https://robohash.org/earumdoloribusculpa.png?size=50x50&set=set1',
    university: 'Catholic Theological Union',
    department: 'Research and Development',
  },
  {
    id: 93,
    fullName: 'Rosanne Law',
    avatar: 'https://robohash.org/culpavoluptatemcum.png?size=50x50&set=set1',
    university: 'Islamic Azad University, Tehran South',
    department: 'Training',
  },
  {
    id: 94,
    fullName: 'Mollee Hutley',
    avatar: 'https://robohash.org/sedexcepturisuscipit.png?size=50x50&set=set1',
    university: 'Arba Minch University',
    department: 'Marketing',
  },
  {
    id: 95,
    fullName: 'Konstance Ashmore',
    avatar:
      'https://robohash.org/perspiciatisnobistemporibus.png?size=50x50&set=set1',
    university: 'Dominican College',
    department: 'Business Development',
  },
  {
    id: 96,
    fullName: 'Gregory Bawme',
    avatar: 'https://robohash.org/etsolutamollitia.png?size=50x50&set=set1',
    university: 'Alpha Omega University',
    department: 'Human Resources',
  },
  {
    id: 97,
    fullName: 'Earle Bradfield',
    avatar: 'https://robohash.org/sednostrumeius.png?size=50x50&set=set1',
    university: 'Visvesvaraya Technological University',
    department: 'Research and Development',
  },
  {
    id: 98,
    fullName: 'Allis Hallifax',
    avatar: 'https://robohash.org/quidemexplicaboeaque.png?size=50x50&set=set1',
    university: 'Sumy National Agrarian University',
    department: 'Sales',
  },
  {
    id: 99,
    fullName: 'Alan McPaik',
    avatar: 'https://robohash.org/vitaequasad.png?size=50x50&set=set1',
    university: 'Hanoi National Economics University',
    department: 'Services',
  },
  {
    id: 100,
    fullName: 'Rupert Calverd',
    avatar: 'https://robohash.org/quamidfugit.png?size=50x50&set=set1',
    university: 'Grace College',
    department: 'Product Management',
  },
  {
    id: 101,
    fullName: 'Myron Frayn',
    avatar: 'https://robohash.org/cumquequosincidunt.png?size=50x50&set=set1',
    university: 'Himeji Institute of Technology',
    department: 'Services',
  },
  {
    id: 102,
    fullName: 'Joelly Fante',
    avatar: 'https://robohash.org/quaeratsediste.png?size=50x50&set=set1',
    university: 'Mars Hill College',
    department: 'Human Resources',
  },
  {
    id: 103,
    fullName: 'Sheelah Ibbison',
    avatar: 'https://robohash.org/etametet.png?size=50x50&set=set1',
    university: 'Oberlin College',
    department: 'Accounting',
  },
  {
    id: 104,
    fullName: 'Tami Grindlay',
    avatar: 'https://robohash.org/earumminimaquidem.png?size=50x50&set=set1',
    university: 'State University of New York Upstate Medical University ',
    department: 'Support',
  },
  {
    id: 105,
    fullName: 'Aguie Krysztofowicz',
    avatar: 'https://robohash.org/possimusquimolestiae.png?size=50x50&set=set1',
    university: 'Barton College',
    department: 'Legal',
  },
  {
    id: 106,
    fullName: 'Arin Ondrich',
    avatar: 'https://robohash.org/totamplaceatalias.png?size=50x50&set=set1',
    university: 'Université de Savoie',
    department: 'Training',
  },
  {
    id: 107,
    fullName: 'Virge Mc-Kerley',
    avatar: 'https://robohash.org/rationeutmolestiae.png?size=50x50&set=set1',
    university: 'Pennsylvania State University - Lehigh Valley',
    department: 'Services',
  },
  {
    id: 108,
    fullName: 'Selina Hancorn',
    avatar: 'https://robohash.org/quamutvoluptatum.png?size=50x50&set=set1',
    university: 'University of Balochistan',
    department: 'Support',
  },
  {
    id: 109,
    fullName: 'Lilah Jiricka',
    avatar:
      'https://robohash.org/officiavoluptatibusaspernatur.png?size=50x50&set=set1',
    university: 'Ernst-Moritz-Arndt Universität Greifswald',
    department: 'Support',
  },
  {
    id: 110,
    fullName: 'Barnabas Parken',
    avatar: 'https://robohash.org/sitnesciuntmaiores.png?size=50x50&set=set1',
    university: 'California Polytechnic State University - San Luis Obispo',
    department: 'Marketing',
  },
  {
    id: 111,
    fullName: 'Micky Jamme',
    avatar: 'https://robohash.org/dignissimosatqueet.png?size=50x50&set=set1',
    university: 'Corporación Educativa Mayor del Desarrollo "Simón Bolivar"',
    department: 'Product Management',
  },
  {
    id: 112,
    fullName: 'Carlos Dixey',
    avatar:
      'https://robohash.org/adipiscidoloremqueminus.png?size=50x50&set=set1',
    university:
      'Pennsylvania State University - Milton S.Hershey Medical Center',
    department: 'Engineering',
  },
  {
    id: 113,
    fullName: 'Weylin Wait',
    avatar: 'https://robohash.org/quiquiut.png?size=50x50&set=set1',
    university: "Tokyo Women's College of Physical Education",
    department: 'Accounting',
  },
  {
    id: 114,
    fullName: 'Bertrando Schwand',
    avatar: 'https://robohash.org/adictasoluta.png?size=50x50&set=set1',
    university: 'Chongqing Technology and Business University',
    department: 'Business Development',
  },
  {
    id: 115,
    fullName: 'Carleen Babalola',
    avatar: 'https://robohash.org/ametaliquamveritatis.png?size=50x50&set=set1',
    university: 'San Jose State University',
    department: 'Business Development',
  },
  {
    id: 116,
    fullName: 'Dorolisa Lefort',
    avatar: 'https://robohash.org/nequenatusaut.png?size=50x50&set=set1',
    university: 'Susquehanna University',
    department: 'Legal',
  },
  {
    id: 117,
    fullName: 'Linda Grahl',
    avatar:
      'https://robohash.org/consequunturillumfacilis.png?size=50x50&set=set1',
    university: 'University of Science and Technology',
    department: 'Training',
  },
  {
    id: 118,
    fullName: 'Maryjane Skinn',
    avatar:
      'https://robohash.org/laboriosamquismaiores.png?size=50x50&set=set1',
    university: 'Southwest Jiaotong University',
    department: 'Research and Development',
  },
  {
    id: 119,
    fullName: 'Chariot Izzard',
    avatar: 'https://robohash.org/culpalaborumut.png?size=50x50&set=set1',
    university: 'Veer Surendra Sai University of Technology',
    department: 'Business Development',
  },
  {
    id: 120,
    fullName: 'Ike Wingeat',
    avatar:
      'https://robohash.org/molestiaeomnisnesciunt.png?size=50x50&set=set1',
    university: 'Pontifícia Universidade Católica de Minas Gerais',
    department: 'Training',
  },
  {
    id: 121,
    fullName: 'Myrle Brabender',
    avatar: 'https://robohash.org/idperspiciatissit.png?size=50x50&set=set1',
    university: 'Islamic Azad University, Shabestar',
    department: 'Human Resources',
  },
  {
    id: 122,
    fullName: 'Robinet Downey',
    avatar: 'https://robohash.org/undeeanihil.png?size=50x50&set=set1',
    university: 'Universiti Malaysia Perlis',
    department: 'Product Management',
  },
  {
    id: 123,
    fullName: 'Garrot Kubat',
    avatar: 'https://robohash.org/nonatdistinctio.png?size=50x50&set=set1',
    university: 'Hankuk Aviation University',
    department: 'Sales',
  },
  {
    id: 124,
    fullName: 'Thom Faltin',
    avatar: 'https://robohash.org/eaqueetanimi.png?size=50x50&set=set1',
    university: 'Laurus Technical Institute',
    department: 'Business Development',
  },
  {
    id: 125,
    fullName: 'Adah Hallgate',
    avatar: 'https://robohash.org/iustoaperiamquos.png?size=50x50&set=set1',
    university: 'Institute of Social Studies',
    department: 'Human Resources',
  },
  {
    id: 126,
    fullName: 'Marillin Quade',
    avatar: 'https://robohash.org/illumiustosoluta.png?size=50x50&set=set1',
    university: 'Lutherische Theologische Hochschule Oberursel',
    department: 'Accounting',
  },
  {
    id: 127,
    fullName: 'Anjanette Biers',
    avatar: 'https://robohash.org/quisminusatque.png?size=50x50&set=set1',
    university: 'Kuban State University of Agriculture',
    department: 'Research and Development',
  },
  {
    id: 128,
    fullName: 'Hayley Jacquest',
    avatar: 'https://robohash.org/adipiscicumaliquam.png?size=50x50&set=set1',
    university: 'Janus Pannonius University',
    department: 'Business Development',
  },
  {
    id: 129,
    fullName: 'Hailey Papps',
    avatar: 'https://robohash.org/idnesciuntomnis.png?size=50x50&set=set1',
    university: 'Osaka City University',
    department: 'Support',
  },
  {
    id: 130,
    fullName: 'Juieta Boyat',
    avatar: 'https://robohash.org/doloreveniamrepellat.png?size=50x50&set=set1',
    university: 'Universidade do Estado do Rio de Janeiro',
    department: 'Training',
  },
  {
    id: 131,
    fullName: 'Dorree Kinig',
    avatar: 'https://robohash.org/corruptinonipsum.png?size=50x50&set=set1',
    university: 'University of California, San Diego',
    department: 'Legal',
  },
  {
    id: 132,
    fullName: 'Marthena Janousek',
    avatar:
      'https://robohash.org/repellendussintcorporis.png?size=50x50&set=set1',
    university: 'University of Southern Queensland',
    department: 'Product Management',
  },
  {
    id: 133,
    fullName: 'Maxine McWhannel',
    avatar: 'https://robohash.org/voluptatemametest.png?size=50x50&set=set1',
    university: 'Université Catholique de Lyon',
    department: 'Marketing',
  },
  {
    id: 134,
    fullName: 'Libbi Addionisio',
    avatar:
      'https://robohash.org/eveniettotamconsequuntur.png?size=50x50&set=set1',
    university: 'Universität Dortmund',
    department: 'Training',
  },
  {
    id: 135,
    fullName: 'Lauree Grishukhin',
    avatar: 'https://robohash.org/solutavelitamet.png?size=50x50&set=set1',
    university: 'University of Bolton',
    department: 'Training',
  },
  {
    id: 136,
    fullName: 'Ajay Mantione',
    avatar: 'https://robohash.org/quietest.png?size=50x50&set=set1',
    university: 'University of Oxford',
    department: 'Research and Development',
  },
  {
    id: 137,
    fullName: 'Hugues Douglas',
    avatar: 'https://robohash.org/omnisutnon.png?size=50x50&set=set1',
    university: 'Qassim Private College',
    department: 'Research and Development',
  },
  {
    id: 138,
    fullName: 'Myles Abley',
    avatar: 'https://robohash.org/utrerumet.png?size=50x50&set=set1',
    university: 'Universitas Kristen Satya Wacana',
    department: 'Accounting',
  },
  {
    id: 139,
    fullName: 'Hedvig Betts',
    avatar: 'https://robohash.org/ipsamidcorrupti.png?size=50x50&set=set1',
    university: 'Hesser College',
    department: 'Training',
  },
  {
    id: 140,
    fullName: 'Wayne MacDermid',
    avatar: 'https://robohash.org/temporaquiafugiat.png?size=50x50&set=set1',
    university: 'University of LaVerne in Athens',
    department: 'Engineering',
  },
  {
    id: 141,
    fullName: 'Harald Geoghegan',
    avatar: 'https://robohash.org/eaestdolore.png?size=50x50&set=set1',
    university: 'Stavropol State University',
    department: 'Human Resources',
  },
  {
    id: 142,
    fullName: 'Annalise Cobbin',
    avatar: 'https://robohash.org/magniiureanimi.png?size=50x50&set=set1',
    university: 'New York College of Podiatric Medicine',
    department: 'Services',
  },
  {
    id: 143,
    fullName: 'Malissa Baroc',
    avatar: 'https://robohash.org/undequissapiente.png?size=50x50&set=set1',
    university: 'Davis and Elkins College',
    department: 'Human Resources',
  },
  {
    id: 144,
    fullName: 'Ernesta Macourek',
    avatar: 'https://robohash.org/quisteneturrerum.png?size=50x50&set=set1',
    university: "Ecole Nationale de l'Aviation Civile",
    department: 'Sales',
  },
  {
    id: 145,
    fullName: 'Town Georgot',
    avatar: 'https://robohash.org/autearumodit.png?size=50x50&set=set1',
    university: 'Jarvis Christian College',
    department: 'Product Management',
  },
  {
    id: 146,
    fullName: 'Goldia Ranking',
    avatar: 'https://robohash.org/nihilestut.png?size=50x50&set=set1',
    university: 'West Pomeranian Business School in Szczecin',
    department: 'Product Management',
  },
  {
    id: 147,
    fullName: 'Lynnett Dabourne',
    avatar: 'https://robohash.org/quidemeosdolorem.png?size=50x50&set=set1',
    university: 'University of Nebraska - Omaha',
    department: 'Business Development',
  },
  {
    id: 148,
    fullName: 'Andres Kaes',
    avatar: 'https://robohash.org/voluptatemeaqui.png?size=50x50&set=set1',
    university: 'Kurgan International University',
    department: 'Legal',
  },
  {
    id: 149,
    fullName: 'Aubrey Casolla',
    avatar: 'https://robohash.org/minimadolorquos.png?size=50x50&set=set1',
    university: 'Cape Coast Polytechnic ',
    department: 'Engineering',
  },
  {
    id: 150,
    fullName: 'Toby Herrero',
    avatar:
      'https://robohash.org/temporaperspiciatisodit.png?size=50x50&set=set1',
    university: 'Gomel State University Francisk Scarnia',
    department: 'Research and Development',
  },
  {
    id: 151,
    fullName: 'Nollie Mitroshinov',
    avatar: 'https://robohash.org/velabut.png?size=50x50&set=set1',
    university: 'University of Gjirokstra "Eqerem Cabej"',
    department: 'Sales',
  },
  {
    id: 152,
    fullName: 'Alex Blindt',
    avatar: 'https://robohash.org/autoditomnis.png?size=50x50&set=set1',
    university: 'Institut des Sciences de la Matière et du Rayonnement',
    department: 'Marketing',
  },
  {
    id: 153,
    fullName: 'Toby Joire',
    avatar:
      'https://robohash.org/magnamdeseruntexcepturi.png?size=50x50&set=set1',
    university: 'Kung Shan Institute of Technology',
    department: 'Research and Development',
  },
  {
    id: 154,
    fullName: 'Joseph Halbeard',
    avatar: 'https://robohash.org/providentutdolor.png?size=50x50&set=set1',
    university: 'Edison Community College',
    department: 'Marketing',
  },
  {
    id: 155,
    fullName: 'Livia Boules',
    avatar: 'https://robohash.org/voluptatemaodio.png?size=50x50&set=set1',
    university: 'Muroran Institute of Technology',
    department: 'Business Development',
  },
  {
    id: 156,
    fullName: 'Zolly Garlant',
    avatar: 'https://robohash.org/fugitsuntnon.png?size=50x50&set=set1',
    university: 'St. Marianna University School of Medicine',
    department: 'Marketing',
  },
  {
    id: 157,
    fullName: 'Masha Ogborn',
    avatar: 'https://robohash.org/autemsintut.png?size=50x50&set=set1',
    university: 'Massachusetts Institute of Technology',
    department: 'Product Management',
  },
  {
    id: 158,
    fullName: 'Jacquie Eskrigg',
    avatar: 'https://robohash.org/quiasitut.png?size=50x50&set=set1',
    university: 'Private Fachhochschule Göttingen',
    department: 'Sales',
  },
  {
    id: 159,
    fullName: 'Pancho Chaffin',
    avatar:
      'https://robohash.org/voluptatumexercitationematque.png?size=50x50&set=set1',
    university: "Hiroshima Women's University",
    department: 'Human Resources',
  },
  {
    id: 160,
    fullName: 'Aylmar Minkin',
    avatar: 'https://robohash.org/doloremisteaut.png?size=50x50&set=set1',
    university: 'Universidad Nacional del Sur',
    department: 'Accounting',
  },
  {
    id: 161,
    fullName: 'Joceline Christoforou',
    avatar:
      'https://robohash.org/rationereiciendisnumquam.png?size=50x50&set=set1',
    university: 'University of Notre Dame',
    department: 'Legal',
  },
  {
    id: 162,
    fullName: 'Lilly Breen',
    avatar: 'https://robohash.org/namaqui.png?size=50x50&set=set1',
    university: 'New England Conservatory of Music',
    department: 'Engineering',
  },
  {
    id: 163,
    fullName: 'Brocky Dayley',
    avatar:
      'https://robohash.org/delectussimiliquereprehenderit.png?size=50x50&set=set1',
    university: 'Dominion College',
    department: 'Human Resources',
  },
  {
    id: 164,
    fullName: 'Genna Botly',
    avatar: 'https://robohash.org/blanditiisfacerevel.png?size=50x50&set=set1',
    university: 'Al Fashir University',
    department: 'Training',
  },
  {
    id: 165,
    fullName: 'Cobb Swinbourne',
    avatar: 'https://robohash.org/aliquamsitquia.png?size=50x50&set=set1',
    university: 'Universidad Libre de Colombia',
    department: 'Marketing',
  },
  {
    id: 166,
    fullName: 'Muriel Fairnington',
    avatar: 'https://robohash.org/corruptinisiqui.png?size=50x50&set=set1',
    university: 'Ecole Nationale Supérieure des Industries Chimiques de Nancy',
    department: 'Accounting',
  },
  {
    id: 167,
    fullName: 'Stearn Vaugham',
    avatar: 'https://robohash.org/veniampariatursaepe.png?size=50x50&set=set1',
    university: 'Universidad Empresarial Siglio 21',
    department: 'Human Resources',
  },
  {
    id: 168,
    fullName: 'Jarret Mouncey',
    avatar: 'https://robohash.org/inperspiciatisvel.png?size=50x50&set=set1',
    university: 'University of the South Pacific',
    department: 'Legal',
  },
  {
    id: 169,
    fullName: 'Quint MacLise',
    avatar: 'https://robohash.org/quieaqueenim.png?size=50x50&set=set1',
    university: 'LICCSAL Business College',
    department: 'Human Resources',
  },
  {
    id: 170,
    fullName: 'Emalia Bellanger',
    avatar: 'https://robohash.org/voluptatemquiquia.png?size=50x50&set=set1',
    university: 'Universidad Motolinía del Pedegral',
    department: 'Services',
  },
  {
    id: 171,
    fullName: 'Lira Darlison',
    avatar: 'https://robohash.org/estveritatismagni.png?size=50x50&set=set1',
    university: 'University of Banja Luka',
    department: 'Human Resources',
  },
  {
    id: 172,
    fullName: 'Wells Deacon',
    avatar:
      'https://robohash.org/voluptasimpeditcupiditate.png?size=50x50&set=set1',
    university: 'Beijing International Studies University',
    department: 'Product Management',
  },
  {
    id: 173,
    fullName: 'Carree McGiffin',
    avatar:
      'https://robohash.org/perferendissitvoluptatum.png?size=50x50&set=set1',
    university: 'Isra University',
    department: 'Accounting',
  },
  {
    id: 174,
    fullName: 'Emmaline McCart',
    avatar: 'https://robohash.org/sedminimadolorem.png?size=50x50&set=set1',
    university: 'National Institute of Technology, Jamshedpur',
    department: 'Services',
  },
  {
    id: 175,
    fullName: 'Evin Desbrow',
    avatar: 'https://robohash.org/nesciuntautlaborum.png?size=50x50&set=set1',
    university: 'Universitas Katolik Soegijapranoto',
    department: 'Research and Development',
  },
  {
    id: 176,
    fullName: 'Prudence Brawson',
    avatar: 'https://robohash.org/architectonamcum.png?size=50x50&set=set1',
    university: 'Dakota State University',
    department: 'Engineering',
  },
  {
    id: 177,
    fullName: 'Bee Ellum',
    avatar: 'https://robohash.org/enimsitqui.png?size=50x50&set=set1',
    university: "Wayo Women's University",
    department: 'Accounting',
  },
  {
    id: 178,
    fullName: 'Sholom Gooddy',
    avatar:
      'https://robohash.org/adipiscitemporacorporis.png?size=50x50&set=set1',
    university: 'Tbilisi State Medical University',
    department: 'Sales',
  },
  {
    id: 179,
    fullName: 'Opalina Mylan',
    avatar: 'https://robohash.org/animisedconsequatur.png?size=50x50&set=set1',
    university: 'Fisk University',
    department: 'Training',
  },
  {
    id: 180,
    fullName: 'Quinta MacCourt',
    avatar:
      'https://robohash.org/voluptaspraesentiumquasi.png?size=50x50&set=set1',
    university: 'Babes-Bolyai University of Cluj-Napoca',
    department: 'Legal',
  },
  {
    id: 181,
    fullName: 'Dallas Cicullo',
    avatar: 'https://robohash.org/etmodiquisquam.png?size=50x50&set=set1',
    university: 'Seisen University',
    department: 'Marketing',
  },
  {
    id: 182,
    fullName: 'Bella Priscott',
    avatar: 'https://robohash.org/sedsuntimpedit.png?size=50x50&set=set1',
    university: 'National College of Ireland',
    department: 'Research and Development',
  },
  {
    id: 183,
    fullName: 'Minerva Gillespey',
    avatar: 'https://robohash.org/ullameaquenulla.png?size=50x50&set=set1',
    university: 'Felician College',
    department: 'Legal',
  },
  {
    id: 184,
    fullName: 'Kylie Alesi',
    avatar: 'https://robohash.org/accusamusatnon.png?size=50x50&set=set1',
    university: 'Fasa Faculty of Medical Sciences',
    department: 'Product Management',
  },
  {
    id: 185,
    fullName: 'Aylmar Heisman',
    avatar:
      'https://robohash.org/cupiditateestquisquam.png?size=50x50&set=set1',
    university: 'Halla University',
    department: 'Engineering',
  },
  {
    id: 186,
    fullName: 'Olivero St. Louis',
    avatar: 'https://robohash.org/doloremsunttempora.png?size=50x50&set=set1',
    university: 'University of St. Gallen',
    department: 'Training',
  },
  {
    id: 187,
    fullName: 'Jourdain Caitlin',
    avatar:
      'https://robohash.org/doloremquedoloremsoluta.png?size=50x50&set=set1',
    university: 'Universidad Nacional de Educación a Distancia',
    department: 'Legal',
  },
  {
    id: 188,
    fullName: 'Tymon Tamburi',
    avatar: 'https://robohash.org/estearepudiandae.png?size=50x50&set=set1',
    university: 'University of Wales, Bangor',
    department: 'Marketing',
  },
  {
    id: 189,
    fullName: 'Vinita FitzGeorge',
    avatar: 'https://robohash.org/nemoquisvitae.png?size=50x50&set=set1',
    university: 'Université Mouloud Mammeri de Tizi Ouzou',
    department: 'Services',
  },
  {
    id: 190,
    fullName: 'Scarlet Timlett',
    avatar: 'https://robohash.org/etfugitveniam.png?size=50x50&set=set1',
    university: 'Sultan Mizan Zainal Abidin Polytechnic',
    department: 'Legal',
  },
  {
    id: 191,
    fullName: 'Marten Downton',
    avatar: 'https://robohash.org/odioidreprehenderit.png?size=50x50&set=set1',
    university: 'Université de Kamina',
    department: 'Business Development',
  },
  {
    id: 192,
    fullName: 'Booth Beal',
    avatar: 'https://robohash.org/blanditiisomnissunt.png?size=50x50&set=set1',
    university: 'Fachhochschule Dortmund',
    department: 'Accounting',
  },
  {
    id: 193,
    fullName: 'Torrance Glassopp',
    avatar: 'https://robohash.org/noneaquenon.png?size=50x50&set=set1',
    university: 'Bashkir State Medical University',
    department: 'Services',
  },
  {
    id: 194,
    fullName: 'Roosevelt Ferbrache',
    avatar: 'https://robohash.org/nostrummolestiasest.png?size=50x50&set=set1',
    university: 'Begum Rokeya University, Rangpur',
    department: 'Marketing',
  },
  {
    id: 195,
    fullName: 'Renato Tipens',
    avatar: 'https://robohash.org/quimollitiamagnam.png?size=50x50&set=set1',
    university: 'Universidad Tecnológica de El Salvador',
    department: 'Accounting',
  },
  {
    id: 196,
    fullName: 'Papageno McNair',
    avatar: 'https://robohash.org/doloremquefugiteum.png?size=50x50&set=set1',
    university: 'University of Burao',
    department: 'Sales',
  },
  {
    id: 197,
    fullName: 'Rea Summerskill',
    avatar: 'https://robohash.org/illumrepellatsint.png?size=50x50&set=set1',
    university: 'University of Kabianga',
    department: 'Support',
  },
  {
    id: 198,
    fullName: 'Lenore Vogelein',
    avatar: 'https://robohash.org/modiquiiste.png?size=50x50&set=set1',
    university: 'University of Arizona',
    department: 'Product Management',
  },
  {
    id: 199,
    fullName: 'Kenna Nial',
    avatar: 'https://robohash.org/quirerumdolorem.png?size=50x50&set=set1',
    university: 'Universitas Trisakti',
    department: 'Legal',
  },
  {
    id: 200,
    fullName: 'Ryun Sangar',
    avatar: 'https://robohash.org/quialiquidest.png?size=50x50&set=set1',
    university: 'Wilson College',
    department: 'Training',
  },
];

data.forEach(({ avatar, department, fullName, university }) => {
  const cardList = document.querySelector('.cardList');
  cardList.insertAdjacentHTML(
    'beforeend',
    `
    <div class="card">
      <div class="left">
        <div class="imageBox">
          <img src="${avatar}" alt="">
        </div>
      </div>
      <div class="right">
        <div class="name">${fullName}</div>
        <div class="info">
          <div class="university>${university}</div>
          <div class="department">${department}</div>
        </div>
      </div>
    </div>`
  );
});
